// <auto-generated />
namespace Zanotuj.To.WebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changerelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changerelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201604021241280_Change relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
